### ISSUE TITLE
Having trouble initalizing the game (1.14.4)

### ISSUE THREAD

**Issue by DatrixTHLK** [SilentChaos512/Silents-Mechanisms#10]
## Versions

- **Silent's Mechanisms**: 0.4.2+23
- **Silent Lib**: 4.3.1+39
- **Forge**: 28.0.73
- **Modpack**: N/A

## Expected Behavior

- No crashing

## Actual Behavior

- Crash to Desktop while initalizing game

## Links/Images

- [(Crash Report)](https://gist.github.com/DatrixTHLK/88e7bce004251624fa51e1b24fb60b19)

## Steps to Reproduce the Problem

1. Other than just starting the game nothing else

**Comment by SilentChaos512** [comment]
Crash report shows Compatched is at fault. Why did you report it here?

(edit) The ItemColors crash is very unpredictable. A change in the mod list can trigger it, but the mod in the stack trace is the one that needs to fix it.

**Comment by DatrixTHLK** [comment]
I took a look at the crash report right after sending this and saw compatched, but was unaware that was a mod I had in my mod list at the time. It only happened when Silent Mechanism was in my mod list when the crash happened so I thought this mod was the culprit. So I will gladly report it to compatched, thanks for the info. My apologies for the honest mistake and I do make a lot of them.

**Comment by SilentChaos512** [comment]
No problem, some of these crashes are hard to figure out. You can add a completely unrelated mod and another one crashes... concurrency is fun.

**Comment by Shadows-of-Fire** [comment]
Well this is only happening because both of us are doing something relating to item color registration at the same time, when neither of us should be. All calls to ItemColors#register should be wrapped in DeferredWorkQueue.runLater since it's sent on the async bus but doesn't appear to have been made synchronized.

**Comment by DatrixTHLK** [comment]
I don't understand the last part (the async bus). Other than that I understand. Thanks for that.
