### ISSUE TITLE
[MC 1.15.2] Can't craft leather from zombie leather after upgrading to 0.8.0+59

### ISSUE THREAD

**Issue by Janitor53** [SilentChaos512/Silents-Mechanisms#100]
## Versions

- **Silent's Mechanisms**: 0.8.0+59
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.31
- **Modpack**: Q-tech

## Expected Behavior

- Able to craft 1 leather from 4 zombie leather

## Actual Behavior

- Not able to craft, recipe does not shown in jei

## Links/Images

- https://i.imgur.com/64qyNC7.png https://i.imgur.com/mzHqfXe.png

**Comment by Wiccat** [comment]
Confirmed issue exists in 1.16.1-0.8.1+62 as well

**Comment by Tafkae** [comment]
Probably related issue: I had a drying rack with zombie leather in it, and breaking the drying rack (without removing the zombie leather) crashed my game. This was on 0.8.0+59 as well.

**Comment by SilentChaos512** [comment]
Not related at all, @Tafkae. Do you have Optifine? If so, that's probably the cause.

**Comment by Tafkae** [comment]
Oh! I do have Optifine, yeah.
