### ISSUE TITLE
Crazy RAM usage/FPS impact of items in JEI

### ISSUE THREAD

**Issue by DeadlyLazy** [SilentChaos512/Silents-Mechanisms#105]
## Versions

- **Silent's Mechanisms**: 0.8.9+59
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.36
- **Modpack**: All the Mods 5-2.18

## Expected Behavior

Searching @Silents in JEI not cause massive FPS drop and RAM usage spike

## Actual Behavior

Searching @Silents in JEI causes massive FPS drop and RAM usage spike

## Links/Images

https://www.youtube.com/watch?v=CafBUcD-yG4

## Steps to Reproduce the Problem

1. Press F3 in game and open inventory
2. Type @Silents in JEI
3. Look at the RAM usage in the top right of the screen and see rapid usage

**Comment by thebrianlenz** [comment]
I have encountered this same problem and have narrowed down the cause to a specific item.

Whenever the "Liquid Starlight Canister" is visible in JEI, there is a significant FPS drop.

- **Silent's Mechanisms**: 0.8.9+74
- **Silent Lib**: 4.9.1+64
- **Forge**: 36.0.45
- **Modpack**: Stacia Expert 1.9.5.4
