### ISSUE TITLE
Crash related to drying rack

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silents-Mechanisms#110]
## Versions

- **Silent's Mechanisms**: 0.8.0+59
- **Silent Lib**: 4.6.6+59
- **Minecraft**: 1.15.2
- **Forge**: 31.2.41
- **Modpack**: The New Adventure - https://www.curseforge.com/minecraft/modpacks/the-new-adventure

## Expected Behavior
A creeper blew up a tree that had a drying rack with jerky hanging on it. Expected the jerky/drying rack to drop on the ground.

## Actual Behavior
Took the jerky off the rack and the Client crashed to desktop.

## Links/Images
Crash log - https://pastebin.com/EHA6hFU9

## Steps to Reproduce the Problem

1. Place drying rack on tree and create jerky with it.
2. Explode creeper to destroy tree, leaving drying rack suspended in air.
3. Remove jerky from drying rack.

**Comment by SilentChaos512** [comment]
Optifine issue, nothing I can do about it.

**Comment by ghost** [comment]
Ah, I had forgotten about adding Optifine. Thanks!
