### ISSUE TITLE
[1.16.3] Unable to log in to dedicated server -malformed input around byte 59

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/Silents-Mechanisms#111]
## Versions

- **Silent's Mechanisms**: SilentMechanisms-1.16.3-0.8.2+66.jar

- **Silent Lib**: SilentLib-1.16.3-4.8.1+61.jar
- **Forge**: 34.1.5
- **Modpack**: TownCraft TWO for 1.16.3

## Actual Behavior

- unable to log in to multiplayer server.

## Links/Images

- (Link)
![image](https://user-images.githubusercontent.com/4427684/95004989-d4a60d80-05af-11eb-9ae9-9706cde7a09b.png)
[Client- latest.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/5322550/Client-.latest.log)
[Server-debug.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/5322552/Server-debug.log)
[Server-latest.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/5322553/Server-latest.log)

## Steps to Reproduce the Problem

Make a dedicated server with only silents mech and silent lib and log in to it.

**Comment by ProsperCraft** [comment]
Still an issue in SilentMechanisms-1.16.3-0.8.2+66.jar

![image](https://user-images.githubusercontent.com/4427684/95005875-b560ad80-05ba-11eb-8281-d71dd8f4af56.png)

**Comment by ProsperCraft** [comment]
I checked and silent Gear is fine, it is only Mechanisms.

**Comment by SilentChaos512** [comment]
With version 0.8.3? Not having any issues connecting to a server in dev.

**Comment by ProsperCraft** [comment]
SilentMechanisms-1.16.3-0.8.2+66

**Comment by ProsperCraft** [comment]
I see now, curseforge wasn't feeding me the right version, retesting.

**Comment by ProsperCraft** [comment]
ok, I am not crazy - 
![image](https://user-images.githubusercontent.com/4427684/95005999-497f4480-05bc-11eb-92cf-5a0072eba5d4.png)

SilentMechanisms-1.16.3-0.8.2+66

**Comment by SilentChaos512** [comment]
https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms/files/3071366

**Comment by ProsperCraft** [comment]
Confirmed fix, thank you.
