### ISSUE TITLE
Copper overrides other mods

### ISSUE THREAD

**Issue by chrifox** [SilentChaos512/Silents-Mechanisms#113]
## Versions
SilentMechanisms-1.16.3-0.8.3+67.jar
SilentLib-1.16.3-4.8.1+61.jar
Forge-34.1.5

## Expected Behavior
Ores from other mods should smelt into ingots from the original/same mod.

## Actual Behavior
Immersive engineering copper ore smelts into silent's mechanisms copper ingot and cannot then be used in the engineer's workbench.

## Steps to Reproduce the Problem
1. Place a copper ore from immersive engineering into a furnace with fuel.
2. Wait.
3. See copper ingot from silent's mechanisms as output

**Comment by SilentChaos512** [comment]
I agree about the smelting recipes, but you should report the ingots not working to IE. My ingots are correctly tagged, so nothing I can do about that part.

**Comment by chrifox** [comment]
Gotcha, thanks very much
