### ISSUE TITLE
Uranium repairs anything and can swap materials in crafting

### ISSUE THREAD

**Issue by Jameshenrik** [SilentChaos512/Silents-Mechanisms#118]
I'm using the 1.16.3 version, and all of my tools can be repaired using uranium in an anvil. Also, if I swap a material (i.e diamond) with another material (i.e iron) when crafting a tool part, tip upgrade, etc. then the output item will stay the same (so I can craft a diamond sword with iron) - this doesn't work if you remove the material before switching it. ![Base Profile Screenshot 2020 11 03 - 00 16 03 44](https://user-images.githubusercontent.com/73860229/97933335-626d4800-1d6a-11eb-8039-26dc411495fe.png)
) oh and also, there are no regular upgrades other than tip upgrades? the upgrade base is still there and when I played in 1.15.2 I could use them to craft upgrades but now they do nothing. idk if u knew about this one or not

**Comment by SilentChaos512** [comment]
First of all, wrong repo. Should have been on Silent Gear.

Not sure what you mean about uranium repairing anything. Materials can repair items of the same tier or lower. iirc uranium is a fairly high tier.

The crafting issue you describe has been reported before. No one has gotten back to me with a cause, but it has to be the fault of another mod. Probably one that changes the crafting system in some way. The issue does not occur normally.
