### ISSUE TITLE
Lava generator not making power

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silents-Mechanisms#12]
## Versions

- **Silent's Mechanisms**: 1.14.4-0.5.1+25
- **Silent Lib**: 1.14.4-4.3.2+42
- **Forge**: 28.0.95
- **Modpack**: N/A

## Expected Behavior

Put lava bucket in Lava Generator and make power

## Actual Behavior

Lava bucket goes into lava gen inventory but no power produced. No Lava consumed

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. put lava bucket in lava generator
2. nothing happens, no power produced
3.

Maybe have a way for any fluid container with lava in to be right clicked on lava generator to fill it

**Comment by SilentChaos512** [comment]
I fix one bug and make another in the process XD

**Comment by ghost** [comment]
its all good - cant be modding without a few unexpected things happening, lol. Im loving your tech mod Mechanisms. Cant wait for the new stuff youve got lined up !

**Comment by SilentChaos512** [comment]
As a temporary workaround, you can place an empty bucket in the bottom slot and it should accept lava.

**Comment by ghost** [comment]
indeed yes that does work
