### ISSUE TITLE
[1.16.3] Add a dimension blacklist for Oil Lakes, what dimensions it shouldn't spawn in etc.

### ISSUE THREAD

**Issue by Gbergz** [SilentChaos512/Silents-Mechanisms#120]
## What Should Be Added or Changed?
Add a dimension blacklist for Oil Lakes, what dimensions it shouldn't spawn in etc.
## Why Should This Be Done?
Currently the Mining Dimension in my modpack is overflowing with oil lakes, would be neat to get a blacklist to get rid of oil lakes in there.

**-** Gbergz

**Comment by Gbergz** [comment]
Still kinda need this.
Is this something that could be implemented?

**Comment by SilentChaos512** [comment]
Yeah, should be possible. I'll take a look at it this weekend.
