### ISSUE TITLE
Missing Infuser Textures

### ISSUE THREAD

**Issue by RainnMannx** [SilentChaos512/Silents-Mechanisms#121]
Silent's Mechanisms 0.8.7+72

Expected Behavior
Infuser to have textures.

Actual Behavior
Infuser has no textures.

Infusers json points to a spot that does not contain the textures.

**Comment by SilentChaos512** [comment]
Fixed in 1.0.0 by f6f2f3377169e1c2db55de525e59e5a805c7a8da
