### ISSUE TITLE
Crash when placing a Coal Generator in the World 

### ISSUE THREAD

**Issue by Freebi85** [SilentChaos512/Silents-Mechanisms#126]
## Versions

- **Silent's Mechanisms**: SilentMechanisms-1.16.3-0.8.7+72
- **Silent Lib**: SilentLib-1.16.3-4.9.0+63
- **Forge**: 35.1.7
- **Modpack**: custom. not public yet.

## Expected Behavior
To not crash^^

## Actual Behavior
Crash due to placing coal generator in the world.

## Links/Images
[crash-2020-12-12_11.30.02-server.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/5682892/crash-2020-12-12_11.30.02-server.txt)

## Steps to Reproduce the Problem
1. Place a Coal Generator in the world.

**Comment by SilentChaos512** [comment]
"Tag used before bound." So that issue still happens. Strange that I never encounter this during testing.

Just going to link the fix for my own reference, so I don't have to search for it again: https://github.com/SilentChaos512/Silent-Gear/commit/cf15d4e20f01023931cd16048076311c56698a4e

**Comment by Gbergz** [comment]
Still happens in latest version apparently. 
https://www.curseforge.com/minecraft/mc-mods/silents-mechanisms/files/3138430

Crash report
https://pastebin.com/CmprspWq

Modpack: TNP Limitless 3, v1.8.3

**Comment by SilentChaos512** [comment]
Seems the fetchTags method is client-side only for some reason. I assume that crash was on a server, @Gbergz?  That's... frustrating. I thought that was a client-only crash. Wish we could figure out which mod is causing this to happen.

**Comment by Gbergz** [comment]
Yeah It's on a server. But it happens in single player too it seems. People reported it.

**Comment by Dryelo** [comment]
happened to me as well:
Minecraft v1.16.4
forge-1.16.4-35.1.36
SilentLib-1.16.3-4.9.0+63
SilentMechanisms-1.16.3-0.8.8+73

Modpack: TNP Limitless 3 plus a few personal favorites

I'll post my crash log here, it might help you locating the bug.

Cheers!

[crash-2021-01-12_23.28.30-server.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/5805320/crash-2021-01-12_23.28.30-server.txt)

**Comment by Gbergz** [comment]
Still happening and it's pretty annoying. Full discussion here: https://github.com/The-Nexus-Project/Limitless-3/issues/74

**Comment by SilentChaos512** [comment]
Alright, I'll see if I can hack my already nasty hack to work around whatever broken mod is causing this...

**Comment by ktremain** [comment]
possible culprit identified in this thread:
https://github.com/The-Nexus-Project/Limitless-3/issues/74#issuecomment-754229084
"EDIT 2 I have now confirmed that it is in fact "Alexsmobs" causing the issue"
Dont know if this will help you in finding a less hacky workaround or not?....

**Comment by SilentChaos512** [comment]
Version 0.8.9 has a new workaround that might prevent the crash at least. Not sure if the generator will still accept fuel in cases where the crash would have occurred, but I think it will.

**Comment by Bi11yKid** [comment]
Latest version seems to work on the server side, but the client game crashed for me when trying to access the coal generator

[crash-2021-01-20_19.15.38-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/5846177/crash-2021-01-20_19.15.38-client.txt)

I am hosting a server for TNP Limitless 3, just updated the mod on the server and my client to the latest version.  before the server would crash on startup, but now the server seems stable, whilst the client crashed.  After a bit of extra testing i found that after updating, right clicking on anything causes the client to crash

**Comment by SilentChaos512** [comment]
@Bi11yKid Your crash report shows Simple Farming is at fault.

**Comment by Bi11yKid** [comment]
I saw that too, but the only change I made was updating this mod
