### ISSUE TITLE
No way to make Redstone Alloy Ingot

### ISSUE THREAD

**Issue by revdave33** [SilentChaos512/Silents-Mechanisms#13]
## Versions

- **Silent's Mechanisms**: 1.14.4-0.5.1+25
- **Silent Lib**: 1.14.4-4.3.2+42
- **Forge**: 28.0.100
- **Modpack**: N/A

## Actual Behavior

I want to make any one of the machines -- and use them. I am able to make the Basic Alloy Smelter, but there is no way to power it.

It needs Redstone Alloy Ingots, but the recipe for the Redstone Alloy Dust that could be smelted into ingots is missing. The only way to make the ingots is through the Alloy Smelter, the only way to make a generator to power the smelter needs ingots.

**Comment by steroyle** [comment]
> ## Versions
> * **Silent's Mechanisms**: 1.14.4-0.6.9+42
> * **Silent Lib**: 1.14.4-4.4.0+44
> * **Forge**: 28.1.96
> * **Modpack**: All the Mods 4

I seem to be having the same issue, there is no way to create Redstone Alloy Dust or Redstone Alloy Ingots and the changes in [a22d460](https://github.com/SilentChaos512/Silents-Mechanisms/commit/a22d460efd0ef0ad5a202b7cb5088ae03399a27e) don't seem to resolve this specific issue.
