### ISSUE TITLE
Welcome message causing error for clients when joining

### ISSUE THREAD

**Issue by jr-brown** [SilentChaos512/Silents-Mechanisms#130]
### Versions

- **Silent's Mechanisms**: 0.8.5+69
- **Silent Lib**: 4.8.1+61
- **Forge**: 34.1.42
- **Modpack**: New Beginnings 2

## Issue

Setup a server using OwlyCurseServerCreator for New Beginnings 2.
When connecting from both local machine and other clients, the error The received string length is longer than maximum allowed 141>128 occours.
I believe this is due to the welcome message from this modpack. Disabling welcome message in the config for both client and server does not affect issue.

**Comment by SilentChaos512** [comment]
That's incredibly vague. Anything in the log file that indicates SilMech is at fault? Minecraft sends a lot of data to clients on connect.  That could be from anything. Even recipes encode strings to send to clients.

**Comment by jr-brown** [comment]
Apologies, I wasn't aware that other messages might be sent, although the chat message is near the right length (~145). If no-one else has this issue running this modpack on a server then it's probably not the problem.
