### ISSUE TITLE
Badly compressed packet

### ISSUE THREAD

**Issue by Christofmeg** [SilentChaos512/Silents-Mechanisms#133]
**Versions:**
SilentMechanisms-1.16.3-0.8.9+74
SilentLib-1.16.3-4.9.1+64
SilentGear-1.16.3-2.5.4+212
SilentGems-1.16.3-3.7.9+112
Forge: 1.16.5 36.0.4
+ 136 other mods: https://pastebin.com/dBuptJti

**Info:**
This only occurs when trying to join a server with the listed mods.
Installing either and/or both SilentMechanisms and SilentGems results in this error. 

**Issue:**
Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2113173 is larger than protocol maximum of 2097152

**Comment by SilentChaos512** [comment]
Got a log file? Or any information I can work with? I've never encountered this issue before.

**Comment by Christofmeg** [comment]
[latest.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/5888552/latest.log)

**Comment by SilentChaos512** [comment]
Do you have access to the server log?

**Comment by SilentChaos512** [comment]
Also just noticed this line: `Client has mods that are missing on server: [silents_mechanisms, silentgems]`. That might be related.

**Comment by Christofmeg** [comment]
Well I don't know what could be causing this else than forge 1.16.5 being in beta.

![compressed packet](https://user-images.githubusercontent.com/4357405/106172149-c1d4cb80-6192-11eb-9f07-53b09f9c8eba.PNG)
[latest.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/5888822/latest.log)
![Compatible](https://user-images.githubusercontent.com/4357405/106172155-c4cfbc00-6192-11eb-8764-d6d2e7aedcd5.PNG)

**Comment by Christofmeg** [comment]
Well apparently using this mod fixed the issue. https://www.curseforge.com/minecraft/mc-mods/xl-packets.
So the issue had something to do with the size of packets being sent to client.
