### ISSUE TITLE
Infuser missing texture

### ISSUE THREAD

**Issue by ChromaPIE** [SilentChaos512/Silents-Mechanisms#135]
## Versions

- **Silent's Mechanisms**: 1.16.3-0.8.10+75
- **Silent Lib**: 1.16.3-4.9.1+64
- **Forge**: 36.0.42
- **Modpack**: N/A

## Expected Behavior

- Correctly shown texture for the Infuser

## Actual Behavior

- The Infuser showing a missing texture.

**Comment by SilentChaos512** [comment]
Duplicate of #121
