### ISSUE TITLE
Incompatible with JEI 7.6.3+

### ISSUE THREAD

**Issue by bozmund** [SilentChaos512/Silents-Mechanisms#139]
## Versions

- **Silent's Mechanisms**: 1.0.0+76
- **Silent Lib**: 4.9.6
- **Forge**: 36.1.0
- **Modpack**: personal

## Expected Behavior

- I think it should just render correctly i think.

## Actual Behavior

- It renders incorrectly liquid starlight

## Links/Images

[crash-2021-04-11_14.14.54-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/6291734/crash-2021-04-11_14.14.54-client.txt)
[crash-2021-04-11_14.14.54-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/6291735/crash-2021-04-11_14.14.54-client.txt)
https://gist.githubusercontent.com/natanfudge/db08359a9abdc0f93aa6af761bd6cfc6/raw/de1c7f3b78bad67038f34c8cc976c40cfada9676/crash.txt

## Steps to Reproduce the Problem

1.Have sil mech and astral sorcery instaled i think
2.go in jei and type @silent
3.scroll until u get to items for sil mechs and then the game closes

**Comment by medsal15** [comment]
I am having the same crash with other modded fluids, on forge 36.1.4, with the same version of silent lib and silent mechanisms. The game crashes the moment it attempts to render canisters.

Do note that the game does not crash without using JEI.

**Comment by bozmund** [comment]
It is a issue with the current version of JEI. As soon as I loaded previous version, the page where the liquids are it is crashing no more although it is a little laggy
