### ISSUE TITLE
Crash while looking in creative menu/GUI glitch if using JEI

### ISSUE THREAD

**Issue by XxPyroGhostxX** [SilentChaos512/Silents-Mechanisms#141]
## Versions

- **Silent's Mechanisms**: 1.16.3-1.0.1+77.jar
- **Silent Lib**: 1.16.3-4.9.0+63
- **Forge**: 1.16.5-forge-36.0.55
- **Modpack**: Custom(personal)

## Expected Behavior
To be able to view all inclueded items/blocks using the creative menu tab or the JEI GUI while in survival

## Actual Behavior
unresponcive JEI GUI but no game crash or while Scrolling down in the "Silent Mechanisms" creative menu tab Game Crash.

## Links/Images
Crash report links: 
1st - https://www.dropbox.com/s/35q542l737ggmxh/crash-2021-04-06_23.17.56-client.txt?dl=0
2nd - https://www.dropbox.com/s/h8xwfjjc3c7mjga/crash-2021-04-16_23.30.15-client.txt?dl=0
3rd - https://www.dropbox.com/s/hts9i8k268g5gj3/crash-2021-04-17_01.00.54-client.txt?dl=0
the abouve crash reports are with my full Mod list, The crash report below is only botania (+ required Dependencies) and Indusrtail Forgoing (+ required Dependencies)
https://www.dropbox.com/s/thdk1y2gfa4jujn/crash-2021-04-17_01.54.28-client.txt?dl=0

![2021-04-17_01 58 57](https://user-images.githubusercontent.com/82684543/115095219-c18dd600-9f20-11eb-9e9e-b7bc61271301.png)
![2021-04-17_01 59 11](https://user-images.githubusercontent.com/82684543/115095226-c6eb2080-9f20-11eb-898e-3893a5e26cde.png)
![2021-04-17_01 59 17](https://user-images.githubusercontent.com/82684543/115095227-c8b4e400-9f20-11eb-87a7-4ef8d64d93f3.png)
![2021-04-17_01 59 25](https://user-images.githubusercontent.com/82684543/115095229-cb173e00-9f20-11eb-9e18-212ae0049300.png)
![2021-04-17_01 59 35](https://user-images.githubusercontent.com/82684543/115095231-cd799800-9f20-11eb-8cfe-a6355e860400.png)
![2021-04-17_01 59 44](https://user-images.githubusercontent.com/82684543/115095233-d0748880-9f20-11eb-8ac2-c915ab3797ea.png)

## Steps to Reproduce the Problem

1. install "industrial-foregoing-1.16.4-3.2.8.1-f2c848c" and "titanium-1.16.4-3.2.5"
2. Enter creative and open creative menu and find "Silent Mechanisms"tab, scroll down to get the Crash
3. Type in the JEI serch bar "SL, SLI or SLU" to get the unresponcive JEI but no crash
4. reverting to "SilentMechanisms-1.16.3-1.0.0+76" fixes the problem

**Comment by SilentChaos512** [comment]
You need to update to a newer version of JEI. SilMech 1.0.1 fixed a crash with a recent JEI update, so unfortunately you have to update both mods together.

**Comment by XxPyroGhostxX** [comment]
@SilentChaos512  Thank you for the fats responce, i have updated to the latest JEI and i can confirm that the issue does in fact go away. thank you again. keep up the great work with the mods.
