### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ApolloReaper** [SilentChaos512/Silents-Mechanisms#142]
[crash-2021-04-19_00.43.21-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/6333812/crash-2021-04-19_00.43.21-client.txt)

**Comment by najlitarvan** [comment]
what were you doing when it crashed?

**Comment by ApolloReaper** [comment]
was typing copper in jei and it crashed as soon as i hit the p

**Comment by SilentChaos512** [comment]
Please follow the issue template next time. This issue has already been fixed. Update SilMech to 1.0.1 and keep JEI at version 7.6.3 or higher.
