### ISSUE TITLE
Game crashes when searching certain items

### ISSUE THREAD

**Issue by Lequals** [SilentChaos512/Silents-Mechanisms#143]
## Versions
1.16.4

- **Silent's Mechanisms**: 1.0.1+77
- **Silent Lib**: 4.9.6 
- **Forge**: 35.1.36
- **Modpack**: N/A

## Expected Behavior
Tried to search up items such as refinery in the creative search bar 

Going back to previous version of SilentsMechanisms fixes the issue.

## Actual Behavior
Game crashes when typing ref

https://pastebin.com/1kYspSvU

**Comment by SilentChaos512** [comment]
You need to update JEI as well if you are using SilMech 1.0.1.
