### ISSUE TITLE
Liquid Starlight Canister in JEI causing FPS drop

### ISSUE THREAD

**Issue by ksteinwand** [SilentChaos512/Silents-Mechanisms#144]
If the Liquid Starlight (Astral Sorcery) Canister (Silents Mech) is appearing in JEI frames drop from over 100 to 10. Remove the icon from JEI or close out of JEI and frames back to normal. 

![image](https://user-images.githubusercontent.com/59071007/117487746-19709900-af31-11eb-8133-e3ae63647723.png)
![image](https://user-images.githubusercontent.com/59071007/117487788-28efe200-af31-11eb-939c-3d92fb3a0f30.png)

Viewing only canisters from Silents Mechanisms causes even more FPS drops, Liquid Starlight is the only one I have zero'd in on and found a massive decrease in FPS.

**Comment by najlitarvan** [comment]
versions please.
also please include a log

**Comment by ksteinwand** [comment]
SilentMechanisms-1.16.3-0.8.9+74.jar

it doesn't crash, so there is no crash log to provide.

**Comment by najlitarvan** [comment]
not a crash log, an instance log in the folder: logs
what about silent lib
and the version of astral and it's dependencies

**Comment by ksteinwand** [comment]
[latest.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/6443473/latest.log)

silent-lib-1.16.3-4.9.6
silent-gear-1.16.3-.2.6.14

astralsorcery-1.16.4-1.13.9
curios-forge-1.16.5-4.0.5.0
observerlib-1.16.4-1.5.1

**Comment by najlitarvan** [comment]
thank you, please include these things with any issue you are reporting, with any dev

**Comment by ksteinwand** [comment]
First time reporting issues like this. 

Thank you for your patience and wisdom.

**Comment by najlitarvan** [comment]
had to deal with absolute idiots before(which you are not), compared to them this is like a moderate wind to a level 5 tornado

**Comment by ksteinwand** [comment]
Currently in school for stuff like this so good to learn! (I only just did Intro to IT so its not like i'm that well versed yet).

**Comment by SilentChaos512** [comment]
Update to a more recent version. Be sure to update JEI as well, or you will crash. Also see issue #139.
