### ISSUE TITLE
There is an error with the JEI

### ISSUE THREAD

**Issue by DanDanPessoal** [SilentChaos512/Silents-Mechanisms#148]
## Versions

- **Silent's Mechanisms**: 1.16.3-1.0.1+77
- **Silent Lib**: 1.16.3-4.9.6
- **Forge**: 36.1.0
- **Modpack**: I couldn't upload a zip with the mods, so I sent a picture of the mods from my modpack
![modpack](https://user-images.githubusercontent.com/53344909/124227090-7d05e580-dae0-11eb-9aa5-47cbeffe2348.PNG)

## Expected Behavior
 I was hoping to be able to see the recipe of all the recipes through the JEI

- (Description)

## Actual Behavior
When I get to the last page of the JEI to see the mod items, minecraft stops responding, then crashes

- (Description)

## Links/Images
Link for reports 
crashed: https://www.dropbox.com/home?preview=crash-2021-07-02_02.08.47-client.txt

Until the penultimate page of the JEI, I have no problems,
But when I try to go to the last page, it stops responding
![image](https://user-images.githubusercontent.com/53344909/124228748-028a9500-dae3-11eb-8856-d7dc6a44ca38.png)
![image](https://user-images.githubusercontent.com/53344909/124228830-20f09080-dae3-11eb-9237-fdb62d20a7b8.png)

And this crash report appears, which is in the dropbox link above
![image](https://user-images.githubusercontent.com/53344909/124229315-c99ef000-dae3-11eb-86c7-16be72701e38.png)

## Steps to Reproduce the Problem

1. I open the world with the mods loaded
2. I open the inventory
3. I try to go to the last page of the **JEI** and then crash

**Comment by SilentChaos512** [comment]
Well, your crash report doesn't seem to exist. And your SilMech version clearly does not match what you say it is. You are on 0.8.9. You tried to hide that and failed. You need to either update SilMech or downgrade to an older version of JEI.

If you modified the SilMech jar file, stop that. Use a data pack. You'll save yourself (and me) a lot of headaches.

**Comment by DanDanPessoal** [comment]
I didn't mean to bother you, sorry, I was really giving an error, and I came looking for a solution, I didn't try to cover anything up, but if it was my mistake, I apologize for the trouble
