### ISSUE TITLE
Incompatibility with the latest version of the Storage Drawers mod

### ISSUE THREAD

**Issue by elowanut** [SilentChaos512/Silents-Mechanisms#15]
## Versions

- **Silent's Mechanisms**: 1.14.4-0.5.2+28 (also tested 25)
- **Silent Lib**: 1.14.4-4.3.1+42
- **Forge**: 1.14.4-28.0.102 (also does it on 91)
- **Modpack**: N/A

## Expected Behavior

When using the "compacting drawer" from the Storage Drawers mod (using the latest version, 1.14.4-6.0.2), right click on the drawer to put in, say, a stack of iron ingots. The expected result is that the drawer now contains 64 iron ingots, and displays the icon for ingots/nuggets/blocks on its front face.

## Actual Behavior
The game instantly CTDs, eventually loading up the launcher with a crash report. Note that the crash occurs with any item, even ones that aren't typically used in compacting drawers (e.g. items with no alternate forms, like silk-touched ores, or logs). Note that this only occurs with Silent's Mechanisms loaded. Other mods, including Silent's Lib / Gems / Gear are fine.

## Links/Images

Crash report here:
https://www.dropbox.com/s/znxn0wajgzdfr9v/crash-2019-09-10_11.58.27-client.txt?dl=0

## Steps to Reproduce the Problem

1. Load up a forge modded version of minecraft with silent lib / mechanisms, and the Storage Drawers mod.
2. Start a fresh world, place down a compacting drawer.
3. Right click (try to put items into) the drawer with any item.

**Comment by SilentChaos512** [comment]
Looks like something Storage Drawers will need to fix.

**Comment by elowanut** [comment]
This appears to be fixed in the latest version of Storage Drawers (1.14.4-6.0.3).
