### ISSUE TITLE
Advancement chat issue

### ISSUE THREAD

**Issue by 2iguys** [SilentChaos512/Silents-Mechanisms#17]
## Versions

- **Silent's Mechanisms**: 0.5.2+28
- **Silent Lib**: 4.3.2+42
- **Forge**: 28.0.104
- **Modpack**: N/A

## Expected Behavior
Advancements should show up, but they don't show up properly.

- (Description)

## Actual Behavior

- (Description)

## Links/Images
![2019-09-10_19 16 00](https://user-images.githubusercontent.com/9800376/64663265-13df4a80-d400-11e9-9e5c-cdd0e13c48ef.png)

to Reproduce the Problem

1. Add the mod to a server, with the lib mod
2. craft and place the machine
3. get a message about the achievement, but not a proper one.

**Comment by SilentChaos512** [comment]
Just haven't gotten around to adding the translations yet. Naming things is hard :p

**Comment by 2iguys** [comment]
ahh I see. thanks for clarifying :)
