### ISSUE TITLE
Coal generator accepting new tipes of coal

### ISSUE THREAD

**Issue by Hurifire** [SilentChaos512/Silents-Mechanisms#18]
I tried different mods with tiny coal and others and the generator does not accept anything at all.

**Comment by SilentChaos512** [comment]
Should be fixed in 0.6.0 if the items in question are tagged as `forge:nuggets/coal`. The coal generator will accept any item tagged as `silents_mechanisms:coal_generator_fuels` otherwise.

**Comment by MeinKraft** [comment]
as a side note the Mechanisms Magma coals cant be used in the coal generator either. dont know if this is a bug or on purpose. They can be used in normal vanilla furnace tho   v0.6.5+36
