### ISSUE TITLE
Use Decoration.UNDERGROUND_ORES for ore generation

### ISSUE THREAD

**Issue by Rakambda** [SilentChaos512/Silents-Mechanisms#19]
## What Should Be Added or Changed?
Wouldn't it be more appropriate to generate the ores using `Decoration.UNDERGROUND_ORES` instead of `Decoration.UNDERGROUND_DECORATION`?

https://github.com/SilentChaos512/Silents-Mechanisms/blob/b33923044a5c069d3003fddcae9a8d1f53c2f4de/src/main/java/net/silentchaos512/mechanisms/world/SMWorldFeatures.java#L33

## Why Should This Be Done?

This would allow mods like [YAMDA](https://www.curseforge.com/minecraft/mc-mods/yamda) to contain ores from this mod.

**Comment by SilentChaos512** [comment]
Yeah, I must have selected `UNDERGROUND_DECORATION` by mistake, thanks for pointing that out.
