### ISSUE TITLE
I can't use blaze rods as fuel

### ISSUE THREAD

**Issue by glaceron** [SilentChaos512/Silents-Mechanisms#20]
What should i change in the coal_generators_fuels.json? 
I've tried adding "#minecraft:blaze_rod", to the file, but the coal generator brokes and it doesn't work with anything.
Also, I've tried to delete the coal_generators_fuels.json file and it doesn't work either :c

**Comment by SilentChaos512** [comment]
You want to use `minecraft:blaze_rod` or `#forge:rods/blaze`. A leading `#` means tag, otherwise it's an item.

**Comment by glaceron** [comment]
It works, you are awesome. 
Thank you!!!! ♥♥
