### ISSUE TITLE
Sometimes, Math is hard!

### ISSUE THREAD

**Issue by Nachtflame** [SilentChaos512/Silents-Mechanisms#22]
## Versions
- **Silent's Mechanisms**: 0.6.1+32
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.24
- **Modpack**: "Explore, Loot, Mine!" - as yet unreleased

## Expected Behavior
R-Clicked on Pump to open GUI as had several times previously with no issue.

## Actual Behavior
R-Clicked pump, game crashed due to MATH.  [java.lang.ArithmeticException: / by zero]

## Links/Images
https://pastebin.com/yWiverSK

## Steps to Reproduce the Problem
Unable to reproduce on demand. Logged back into world, GUI opens fine.

**Comment by SilentChaos512** [comment]
Figures I missed a couple of / 0 errors. Will be easy to fix.
