### ISSUE TITLE
Flowing Oil has no Texture

### ISSUE THREAD

**Issue by kaffeekirsche** [SilentChaos512/Silents-Mechanisms#25]
## Versions

- **Silent's Mechanisms**: SilentGear-1.14.4-1.4.2+67
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44
- **Forge**: 1.14.4 - 28.1.30
- **Modpack**: N/A

## Issue 
Flowing oil has no texture. See the screenshot

## Links/Images
![2019-10-03_12 36 33](https://user-images.githubusercontent.com/5018275/66120359-fa828600-e5da-11e9-857b-1cc9f9c73fd2.png)

**Comment by Wiccat** [comment]
I had the same issue, but it was caused by the previous version of optifine.  Confirmed by removing optifine and issue went away.   OptiFine 1.14.4 HD U F4 pre7 fixes this issue.

**Comment by kaffeekirsche** [comment]
Thanks Wiccat for the Information. And Sorry for this Issue, Its not a Mod issue relatete issue. its my mistage
