### ISSUE TITLE
Lava generator won't drop itself.

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silents-Mechanisms#26]
## Versions

Minecraft 1.14.4 release

- **Silent's Mechanisms**: 0.6.2+33
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.26
- **Modpack**: N/A

## Expected Behavior

- The lava generator should drop itself after being broken by a pickaxe.

## Actual Behavior

- The generator won't drop itself.

## Links/Images

- https://www.youtube.com/watch?v=Q4qoh-_r-5k&feature=youtu.be

## Steps to Reproduce the Problem

1. Get a lava generator and pickaxe.
2. Use the pickaxe to break the lava generator.

**Comment by SilentChaos512** [comment]
Forgot to tag the issue, commit is 5fe66a07be84b53d6c308255669790e19fba6a58 for anyone who cares. Also added a bit of code in c44d39edfd4fe6b812a455229bec86f0fdbe5fa9 to check for missing loot tables, so this shouldn't be an issue in the future.

**Comment by ghost** [comment]
Thanks SlientChaos512
