### ISSUE TITLE
No recipe for electrum block and nuggets

### ISSUE THREAD

**Issue by Edivad99** [SilentChaos512/Silents-Mechanisms#27]
## Versions

- **Silent's Mechanisms**: 1.14.4-0.6.3+34
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: 28.1.39
- **Modpack**: N/A

The crafting of electrum nuggets, block and vice versa is missing

**Comment by ghost** [comment]
I am also experiencing the same issue, except that my Forge version is slightly older (28.1.33).
Meanwhile, I will have to cheat in the nuggets instead.
