### ISSUE TITLE
Crash with coal generator

### ISSUE THREAD

**Issue by zedner** [SilentChaos512/Silents-Mechanisms#29]
## Versions

- **Silent's Mechanisms**: 1.14.4 0.6.3 +34
- **Silent Lib**: 1.14.4 - 4.4.0 +44
- **Forge**: 1.14.4 28.1.0
- **Modpack**: N/A

- (Description)
Crash when i place coal in coal power generator.

**Comment by SilentChaos512** [comment]
Need a crash report

**Comment by zedner** [comment]
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 10/8/19 10:00 PM
Description: Ticking block entity

java.lang.NoSuchMethodError: net.minecraftforge.common.ForgeHooks.getBurnTime(Lnet/minecraft/item/ItemStack;)I
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.getBurnTime(CoalGeneratorTileEntity.java:36) ~[?:0.6.3+34] {}
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.consumeFuel(CoalGeneratorTileEntity.java:47) ~[?:0.6.3+34] {}
	at net.silentchaos512.mechanisms.block.generator.AbstractGeneratorTileEntity.func_73660_a(AbstractGeneratorTileEntity.java:87) ~[?:0.6.3+34] {}
	at net.minecraft.world.World.func_217391_K(World.java:621) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367) ~[?:?] {}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112) ~[?:?] {pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622) [?:?] {pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.getBurnTime(CoalGeneratorTileEntity.java:36)
	at net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity.consumeFuel(CoalGeneratorTileEntity.java:47)
	at net.silentchaos512.mechanisms.block.generator.AbstractGeneratorTileEntity.func_73660_a(AbstractGeneratorTileEntity.java:87)

-- Block entity being ticked --
Details:
	Name: silents_mechanisms:coal_generator // net.silentchaos512.mechanisms.block.generator.coal.CoalGeneratorTileEntity
	Block: Block{silents_mechanisms:coal_generator}[facing=south,lit=false]
	Block location: World: (-245,71,125), Chunk: (at 11,4,13 in -16,7; contains blocks -256,0,112 to -241,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Block: Block{silents_mechanisms:coal_generator}[facing=south,lit=false]
	Block location: World: (-245,71,125), Chunk: (at 11,4,13 in -16,7; contains blocks -256,0,112 to -241,255,127), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:621)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:367)

-- Affected level --
Details:
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2094
	Level dimension: DimensionType{minecraft:overworld}
	Level name: 1.14 Mods
	Level seed: 698063211955343314
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: {}
	Level spawn location: World: (-224,71,160), Chunk: (at 0,4,0 in -14,10; contains blocks -224,0,160 to -209,255,175), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 198495 game time, 198495 day time
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 8431 (now: false), thunder time: 47592 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:829)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:764)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:112)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:622)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2540521192 bytes (2422 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		bambooeverything-1.14-1.4.0.jar Bamboo Everything {bambooeverything@1.14-1.4.0 DONE}
		Batty's+Coordinates+PLUS+Mod+for+Forge-1.14.4-0.2.0.jar Batty's Coordinates Plus Mod for Forge {coordinatesplusmod@1.14.4_0.2.0 DONE}
		dankstorage-1.5-pre3.jar Dank Storage {dankstorage@1.5-pre3 DONE}
		elevatorid-1.14.4-1.5.1.jar Elevator Mod {elevatorid@1.14.4-1.5.1 DONE}
		extraanvils-2.1a.jar Extra Anvils {extraanvils@2.1a DONE}
		extragolems-9.0.1.jar Extra Golems {golems@TODO-golems_version DONE}
		ferroustry-1.3a.jar Ferroustry {ferroustry@1.3a DONE}
		gravestone-1.15.1.jar Gravestone Mod {gravestone@1.15.1 DONE}
		Harvest-forge-1.14.4-1.2.10-23.jar Harvest {harvest@version DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		jei-1.14.4-6.0.0.13.jar Just Enough Items {jei@6.0.0.13 DONE}
		metalbarrels-1.3d.jar Metal Barrels {metalbarrels@1.3d DONE}
		MouseTweaks-2.11-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.11 DONE}
		playerplates-1.14.4-forge-1.1.0.jar Player Plates {playerplates@1.14.4-forge-1.1.0 DONE}
		resynth-3.1.0.jar Resynth {resynth@3.1.0 DONE}
		SilentGear-1.14.4-1.4.3+68.jar Silent Gear {silentgear@1.4.3+68 DONE}
		SilentGems-1.14.4-3.4.5+78.jar Silent's Gems 3 {silentgems@3.4.5+78 DONE}
		SilentLib-1.14.4-4.4.0+44.jar Silent Lib {silentlib@4.4.0+44 DONE}
		SilentMechanisms-1.14.4-0.6.3+34.jar Silent's Mechanisms {silents_mechanisms@0.6.3+34 DONE}
		StorageDrawers-1.14.4-6.0.5.jar Storage Drawers {storagedrawers@1.14.4-6.0.3 DONE}
		torchmaster-2.0.0.7-rc0.jar Torchmaster {torchmaster@2.0.0.7-rc0 DONE}
		TreeChoppin-1.14.4-1.2.0.jar TreeChoppin {treechoppin@1.2.0 DONE}
		turf-1.14.4-1.0.0.jar Turf {turf@1.0.0 DONE}
		VanillaTweaks-1.14.4.1.5.9.jar VanillaTweaks {vanillatweaks@1.14.4.1.5.9 DONE}
		WallpaperCraft-1.14.4-1.0.5.jar Wallpapercraft {wallpapercraft@1.0.5 DONE}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 DONE}
		forge-1.14.4-28.1.0-client.jar Minecraft {minecraft@1.14.4 DONE}
	Player Count: 0 / 8; []
	Data Packs: mod:metalbarrels, mod:wallpapercraft, mod:vanillatweaks, vanilla, mod:turf, mod:treechoppin, mod:torchmaster, mod:storagedrawers, mod:silents_mechanisms, mod:silentlib, mod:silentgems, mod:silentgear, mod:resynth (incompatible), mod:playerplates, mod:mousetweaks, mod:jei, mod:ironchest, mod:harvest, mod:gravestone, mod:golems, mod:forge, mod:ferroustry, mod:extraanvils, mod:elevatorid, mod:dankstorage, mod:coordinatesplusmod, mod:bambooeverything
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by SilentChaos512** [comment]
Try updating Forge. Also, you should link the crash report next time, or drag and drop the file. Much cleaner and easier to read that way.

(edit) I should have checked the Forge version in the original post...

**Comment by zedner** [comment]
Updating forge worked i installed 28.1.38 forge and it works, srry about crashlog paste, i tried using dropbox and it was too much struggle just to post a single crashlog, i had to download and install client to PC and i don't wanna learn how that program works cause i don't think ill be using it anytime soon.

**Comment by SilentChaos512** [comment]
Pastebin and Gist are good options. I think Pastebin doesn't even require an account. Gist uses your GitHub account.
