### ISSUE TITLE
Certain Blocks Render Oddly Underwater

### ISSUE THREAD

**Issue by WenXin20** [SilentChaos512/Silents-Mechanisms#32]
## Versions

- **Silent's Mechanisms**: v0.6.4+35
- **Silent Lib**:  v4.4.0+44
- **Forge**: v28.1.44

## Expected Behavior

- Blocks placed underwater should be waterloggable.

## Actual Behavior

- Placing Drying Racks, Battery Boxes, Stone Machine Frames, and Alloy Machine frames underwater will render them incorrectly. Allowing them to be waterlogged could fix this.

## Image

![2019-10-11_22 11 42](https://user-images.githubusercontent.com/12000593/66693943-2f927680-ec74-11e9-915d-1c30df973b56.png)

**Comment by SilentChaos512** [comment]
Not sure it makes sense to allowing waterlogging for the machine frames. What if they were part of a wall or floor? They shouldn't allow water to pass through. The battery box... maybe? But the drying rack definitely.

**Comment by WenXin20** [comment]
Could the machine frames be made to render similarly to glass underwater instead of it being waterlogged?

**Comment by SilentChaos512** [comment]
I'll see what I can do about it. Weird thing is they already use the same code as plain glass blocks. So I'm not exactly sure why they do that.

**Comment by WenXin20** [comment]
Bluepower glass had a similar issue that I reported at Qmunity/BluePower#498, if that helps any.

**Comment by SilentChaos512** [comment]
Yeah, that helps. Seems like inheriting from `StainedGlassBlock` instead of `GlassBlock` fixes the issue. Definitely something Forge should fix eventually.

So that just leaves the battery box. Still not sure what I want to do with that. Waterlogging seems odd since it's almost a full block.

**Comment by WenXin20** [comment]
I suppose it could be left as is. Even vanilla Minecraft has some blocks left over that can't be waterlogged, like the stonecutter, which seems odd to me though.

**Comment by SilentChaos512** [comment]
OK, I'll consider this issue closed. Fixes will be included in next version, should be able to release in the next day or two.
