### ISSUE TITLE
Lava and diesel generators eat buckets

### ISSUE THREAD

**Issue by TheDarkPreacher** [SilentChaos512/Silents-Mechanisms#33]
## Versions

- **Silent's Mechanisms**: 0.6.5+36
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.39
- **Modpack**: Absolute Silence v. 1.3

## Expected Behavior

Lava gen takes vanilla lava bucket, adds 1000 mB to internal tank, exports empty bucket, starts producing power.

## Actual Behavior

Lava gen takes vanilla lava bucket, adds 1000 mB to internal tank, does not export empty bucket, starts producing power. Does not effect lava canisters, those return empty canisters.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Place lava gen
2. Open GUI
3. Place vanilla lava bucket in input slot
4. Wait for empty bucket in output slot

**Comment by NielsPilgaard** [comment]
This also goes for the Diesel Generator.

**Comment by NielsPilgaard** [comment]
Thanks!
