### ISSUE TITLE
[1.14.4] Client crash when placing Silent wire against useless energy cable.

### ISSUE THREAD

**Issue by ProsperCraft** [SilentChaos512/Silents-Mechanisms#36]
## Versions

- **Silent's Mechanisms**: SilentMechanisms-1.14.4-0.6.5+36
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**: forge-1.14.4-28.1.47
- **Modpack**: https://www.curseforge.com/minecraft/modpacks/the-adventures-of-halk

## Actual Behavior

- Client crash

## Links/Images

-https://gist.github.com/ProsperCraft/f9e35a767c552852a6408d7062208b72

## Steps to Reproduce the Problem

1. place a cable against a useless mod cable attached to Engineers decor solar.
2.
3.

**Comment by SilentChaos512** [comment]
This issue and maybe #35 should be fixed in version 0.6.6.
