### ISSUE TITLE
[1.14.4] Server and Client Crash

### ISSUE THREAD

**Issue by Lice2** [SilentChaos512/Silents-Mechanisms#38]
## Versions

- **Silent's Mechanisms**: SilentMechanisms-1.14.4-0.6.6+39.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: 1.14.4-forge-28.1.36
- **Modpack**: N/A

## Expected Behavior

- The server crashes after a while. And sometimes the client.

## Actual Behavior

- It starts to lag and then the server crashes.

## Links/Images

- https://pastebin.com/QU5Mn67V

## Steps to Reproduce the Problem

I have again done the version SilentMechanisms-1.14.4-0.6.5 + 36.jar on it seems to work.

**Comment by SilentChaos512** [comment]
Does this still happen on version 0.6.6?

**Comment by SilentChaos512** [comment]
What other FE-producing/using blocks are you using? More specifically, what's connected to your wires?

**Comment by Nachtflame** [comment]
Believe I may be experiencing something similar - 
https://pastebin.com/VzYQWk3L

In this case, SM is the only energy-generator/consumer in the pack even, and issue happens without fail on world transfer.  Simply get *waiting for server* from **The One Probe**, console showing above paste, until I force close MC.

SilentMechanisms-1.14.4-0.6.7+40
Forge 28.1.69

**Comment by SilentChaos512** [comment]
I wonder if it's trying to load a tile entity from an unloaded chunk? Maybe that's what's happening. I'll have to dig through the world/chunk/region code to really tell what's going on, but if nothing else I can try slipping in a loaded chunk check with the next update.
