### ISSUE TITLE
[1.14.4] Server crash

### ISSUE THREAD

**Issue by kwpugh** [SilentChaos512/Silents-Mechanisms#45]
## Versions

- **Silent's Mechanisms**:  SilentMechanisms-1.14.4-0.6.7+40.jar
- **Silent Lib**:  SilentLib-1.14.4-4.4.0+44.jar
- **Forge**:  forge-1.14.4-28.1.80.jar
- **Modpack**:  Pughland Discovery

## Expected Behavior
 No crashes

- (Description)

## Actual Behavior

After a few hours the server crashes.   I have a coal generator, battery box, crusher, electric furnace, refinery, and mixer all connected via wire.

- (Description)

## Links/Images

Crash report:  https://gist.github.com/kwpugh/ea094391e9e94594a2ba3c96fc216c42

- (Link)

## Steps to Reproduce the Problem

1.
2.
3.

**Comment by SilentChaos512** [comment]
I'm guessing this is a duplicate of #38.

**Comment by kwpugh** [comment]
No more crashes since the fix.
