### ISSUE TITLE
Ethane and Polyethylene bug/glitch/lack of feature

### ISSUE THREAD

**Issue by CriswellCodes** [SilentChaos512/Silents-Mechanisms#49]
## Versions

- **Silent's Mechanisms**: SilentMechanisms-1.14.4-0.6.8+41.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: forge-28.1.80
- **Modpack**: World of Dragons - New Age

## Expected Behavior
Ethane and Polyethylene to have a bucket counterpart so you can make fluid filters for refined storage for these 2 in the fluid crafting grid. Canisters to work for these 2 fluids.

- (Description)

## Actual Behavior
These fluids from Silent's Mechanisms do not have a bucket equivalent (ie, for diesel there's diesel as the standalone fluid but there's also diesel bucket) which means lost buckets if you try to interact with them with a fluid grid (canisters do NOT work) and you can't make fluid filters for refined storage with these two.

- (Description)

## Links/Images
N/A

- (Link)

## Steps to Reproduce the Problem

1. Can not craft in fluid grid.
2.
3.

*Crosslink to WoD-NA issue tracker*
https://github.com/kreezxil/World-of-Dragons-A-New-Age/issues/48

**Comment by CriswellCodes** [comment]
I was corrected in my explanation by the original poster:

T0uchMeToday at 12:22 PM
one thing you got wrong
canisters work, just, they cannot be used like buckets
@Tarlin
Which means you can't make filters in refined storage and can't pick up ethane and polyethylene from refined storage

**Comment by Wabbit0101** [comment]
Ethane and Polyethylene also need to be flagged as gaseous in their Forge fluid attribute setup as well. Currently the buckets indicates a gas (they're inverted) but other mods cannot detect the fluids as such.

**Comment by SilentChaos512** [comment]
Tried to make canisters work with Refined Storage with 35db5055c8653cb33ebbb58270a349b3f852aa9e, but it didn't work out. Refined Storage doesn't seem to like stackable fluid containers. Deletes all but one of them, and only inserts one bucket. Extracting doesn't work at all.
