### ISSUE TITLE
[1.14.4] Zinc not generating

### ISSUE THREAD

**Issue by Boomflex** [SilentChaos512/Silents-Mechanisms#50]
## Versions

- **Silent's Mechanisms**: 0.6.8+41
- **Silent Lib**: 4.4.0+44
- **Forge**: 28.1.90
- **Modpack**: Only Silent Gear, Silent Lin, Silent's Mechanism and World Stripper (for testing)

## Expected Behaviour

- Zinc to generate as per config.

```
[world.gen.ZINC]
			#Minimum Y-coordinate (base height) of veins
			minHeight = 20
			#Number of veins per chunk
			veinCount = 1
			#Maximum Y-coordinate (highest level) of veins
			maxHeight = 60
			#Size of veins
			veinSize = 6
```

## Actual Behavior

- Everything else other than Zinc generates

## Links/Images

- https://i.imgur.com/NS4q3WS.jpg

## Steps to Reproduce the Problem

1. Start new world
2. Strip terrain
3. No Zinc
4. No profit

**Comment by ChilledDayZ07** [comment]
Strange I found it in my world.

**Comment by SilentChaos512** [comment]
Not seeing any issues either... If you find anything out, please give me an update.

We could also check your log file. Search for "zinc", see if anything comes up. Or upload and link it here. I doubt it would have anything, but worth checking.

**Comment by Boomflex** [comment]
Well it can't be a coincidence in a brand new world with only your mods
loaded that Zinc doesn't appear?

**Comment by ChilledDayZ07** [comment]
I literally found some today around y50
