### ISSUE TITLE
Custom crusher datapack recipe not working

### ISSUE THREAD

**Issue by Syndaryl** [SilentChaos512/Silents-Mechanisms#56]
## Versions

- **Silent's Mechanisms**: SilentMechanisms-1.14.4-0.6.9+42.jar
- **Silent Lib**: SilentLib-1.14.4-4.4.0+44.jar
- **Forge**: forge-28.1.96
- **Almost All The Ores**: almostalltheores-1.0.1.0.jar

## Expected Behavior
Datapack would add recipes to crush lignite, bitumous coal, and anthracite into coal dust (Items from Almost All The Ores)

## Actual Behavior
No new crusher recipes

## Links/Images
[SilentsMechanisms_almostalltheores.zip](https://github.com/SilentChaos512/Silents-Mechanisms/files/3964469/SilentsMechanisms_almostalltheores.zip)

Datapack is placed in 
D:\Owner\Documents\Curse\Minecraft\Instances\1.14.4\saves\Toolbelt Dog\datapacks
along with my other datapacks (such as the silentgear extra materials datapack that I am loading successfully).

**Comment by SilentChaos512** [comment]
There are dangling commas on line 5 of your recipes. Fixing that should allow the recipes to load.

**Comment by Syndaryl** [comment]
Thanks! Yes, that did it, perfect!
