### ISSUE TITLE
1.14 World Gen : Increased Zinc Gen

### ISSUE THREAD

**Issue by McKitten** [SilentChaos512/Silents-Mechanisms#58]
## What Should Be Added or Changed?

Increase the standard world generation for zinc by a lot.

Been trying to find it at level 50 and 20 for nearly 1km of hammered tunnel to no avail. Is needed for the Bismuth brass ingot / Smelter upgrade.

**Comment by SilentChaos512** [comment]
There was one other user who had this problem, but I can't replicate it (issue #50). Does increasing zinc spawns in the config help at all?
