### ISSUE TITLE
Dust and Crushed Ore Chunks w/Video

### ISSUE THREAD

**Issue by CarlucciMods** [SilentChaos512/Silents-Mechanisms#60]
Running Latest Version of your mod.

Is pretty simple... 
1. Copper Ore goes into crusher, makes Copper Ore Chunks.
2. Copper Ore Chunks back into the crusher to make dust.
3. I pull the dust out into my inventory and it becomes Ore Chunks again. I made video !

 https://vimeo.com/user79498309/review/382215365/79ee7293b5

This is happening with some other ores as well.

**Comment by SilentChaos512** [comment]
Video link seems to be broken.

**Comment by CarlucciMods** [comment]
https://click.email.vimeo.com/?qs=6934b0c26e0c42949d18b199c7a742a6d871431be0dab793ebbc1b25cc97c4bc9d11283e2c0ccde5b8d05b1b449b2f57768bddd655501697f219f72ddff7bdd2

**Comment by SilentChaos512** [comment]
If you have a mod that converts items with the same tag, that might be the problem. Both ore chunks and dusts are tagged as dusts.

**Comment by CarlucciMods** [comment]
Is this something you can fix on your side to make it more user compatible
with other mods. Can I or you change the tags ? In wouldn't know what mod
does this and I don't think I'd have time to break down other mods to fins
out.

**Comment by CarlucciMods** [comment]
Also this just happening to me on my server other players on the same
server with the same mods loaded not having this issue I believe

**Comment by SilentChaos512** [comment]
If it's not happening to other players, that sounds more like a client-server desync issue. Not sure what could cause that. Double-check you have the same exact mods as the server. Maybe try without Optifine.

If it is a tag issue, you _could_ override the tags with a data pack. But you would need to change many of the mod's recipes as well. The recipes are the reason they are tagged that way. Would be better to identify the mod causing the issue if that's the case.
