### ISSUE TITLE
Blaze Rod dupe

### ISSUE THREAD

**Issue by Yamza** [SilentChaos512/Silents-Mechanisms#64]
## Versions
SilentMechanisms-1.15.2-0.7.0+50.jar
SilentLib-1.15.2-4.6.0+48.jar
Forge: forge-31.0.19
Modpack: [Randomly Added Mods v0.1.9](https://www.curseforge.com/minecraft/modpacks/randomly-added-mods)

Crushing a blaze rod gives 4 blaze powder.
Compressing two blaze powder makes a blaze rod.

## Links/Images
https://i.imgur.com/FdByTVR.png

**Comment by Omnimetatron** [comment]
Also occurs in 1.14

**Comment by Dragnier** [comment]
Easy fix: make crushing only give 2 powder guaranteed and only one extra at a low percentage; perhaps 1-5%.
