### ISSUE TITLE
Sand dupe in Electric furnace

### ISSUE THREAD

**Issue by 1M0N3Y1** [SilentChaos512/Silents-Mechanisms#66]
i dont put any sand in furnace but it always there.
![image](https://user-images.githubusercontent.com/32845477/75038488-24234780-54bf-11ea-9dbf-519af95aaae7.png)
![image](https://user-images.githubusercontent.com/32845477/75038499-27b6ce80-54bf-11ea-8c68-c5f63f655a56.png)
![image](https://user-images.githubusercontent.com/32845477/75038522-2f767300-54bf-11ea-9a45-c31baee761b7.png)
![image](https://user-images.githubusercontent.com/32845477/75038544-3b623500-54bf-11ea-97a7-1746ca624a4c.png)

**Comment by SilentChaos512** [comment]
You need to include the versions section along with the versions of all relevant mods.

Also need more information. I replicated the setup in the screenshot in 1.15.2 and nothing happens.
