### ISSUE TITLE
Thermal Solars Dust Support

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silents-Mechanisms#67]
## What Should Be Added or Changed?

Could you add 2 new dusts. These we be Titanium and Lunar dust. 

## Why Should This Be Done?

It would add ore doubleing/compatibility with the ThermalSolars mod.  Using Silent Mechanisms Crusher we could crush ThermalSolars Titanium/Lunar/Ender Ores into 2 dusts, then smelt them for ore doubleing

To make 1xTier 3 solar panel requires 10,365 Titanium ingots, a bit excessive, so ore doubleing would be a huge advantage here

Ender ore already exists in your mod, its just a case of 2 extra textures and 6? recipes added

Thank You

**Comment by SilentChaos512** [comment]
Probably better suited for JAOPCA, if they don't already support it.
