### ISSUE TITLE
Battery Box State of Charge with Comparators

### ISSUE THREAD

**Issue by theaigcaman** [SilentChaos512/Silents-Mechanisms#72]
## What Should Be Added or Changed?

- When a comparator is placed next to a battery box, output the state of charge as a redstone signal. Full power means 100% SOC, no output means <1/15 state of charge. 

## Why Should This Be Done?

- This would make it possible for responsible fuel usage by turning off generators when batteries are full, instead of wasting huge amounts of fuel when running small loads

**Comment by migmolrod** [comment]
IMHO this should be a high priority task. Right now (playing a modpack) I have to mix this with a battery + wires from other mod to correct fuel usage like you said (in my case I'm using a [schmitt trigger](https://www.minecraftforum.net/forums/minecraft-java-edition/redstone-discussion-and/2980824-redstone-schmitt-triggers) reading the battery level).
