### ISSUE TITLE
Hopper Drying Rack Instant Pull

### ISSUE THREAD

**Issue by ghost** [SilentChaos512/Silents-Mechanisms#73]
## Versions

- **Silent's Mechanisms**: 1.14.4-0.6.13+49
- **Silent Lib**: 1.14.4-4.4.0+44
- **Forge**:28.2.1
- **Modpack**: N/A

## Expected Behavior

Put Rotten Flesh in hopper to feed the drying rack
Wait for item to convert
Pull item from rack
## Actual Behavior

Rotten flesh gets pulled by 2nd hopper before the drying rack has converted it
## Links/Images

setup like this
[https://imgur.com/a/ZrVBOil](https://imgur.com/a/ZrVBOil)

## Steps to Reproduce the Problem

1. Place a hopper feeding into a drying rack. Place a hopper under the drying rack
2. Place rotten flesh in top hopper, it loads it into the drying rack
3. and is instantly pulled into the hopper below, before converting to zombie leather

**Comment by SilentChaos512** [comment]
Might add a drying machine at a later time, but I'm happy with the way drying racks work. It _is_ possible to automate them with certain mods, or a bit of redstone. For example, a timer briefly unlocking a hopper.
