### ISSUE TITLE
breaking a Wire with a pickaxe while the wire was failing to deliver power properly to a crusher caused a crash

### ISSUE THREAD

**Issue by Scorch-Mechanic** [SilentChaos512/Silents-Mechanisms#75]
## Versions

- **Silent's Mechanisms**: 1.15.2-0.7.0+50
- **Silent Lib**: 1.15.2-4.6.0+48
- **Forge**: 31.1.46
- **Modpack**: Valhelsia 2 1.15.2-2.1.6

## Expected Behavior
Obviously, not crashing when breaking a wire with a pickaxe.

## Actual Behavior

I had a wire coming from a battery box feeding two crushers stacked vertically with a hopper between. There has been a persistent problem with the top crusher not receiving power for... some reason. In the past, breaking and re-placing the wire feeding it has fixed the problem. So I went to do that again, breaking the wire in the middle of the two crushers. My game immediately crashed.

## Links/Images
[silents mechanisms wire crash.log](https://github.com/SilentChaos512/Silents-Mechanisms/files/4500421/silents.mechanisms.wire.crash.log)

## Other Notes
This is a customized version of the mod pack that I've added Immersive Portals 0.12(forMc1.15withForge) to, because I think they're as cool as all get out. This requires mixinbootstrap 1.0.2 as well, so that's also installed.

**Comment by Scorch-Mechanic** [comment]
[crash-2020-04-19_14.28.31-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/4500432/crash-2020-04-19_14.28.31-client.txt)
 whoops, forgot the crash report. here it is.

**Comment by Scorch-Mechanic** [comment]
Broke another wire, got another crash. 
[crash-2020-04-29_21.29.26-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/4556152/crash-2020-04-29_21.29.26-client.txt)

**Comment by SilentChaos512** [comment]
Possibly fixed in 0.7.1
