### ISSUE TITLE
remove default machine recipes

### ISSUE THREAD

**Issue by TheNimbleNinja** [SilentChaos512/Silents-Mechanisms#76]
## What Should Be Added or Changed?
support for removing default machine recipes
or craftweaker support :(
- (Description)

## Why Should This Be Done?
lets people use your mod to make differnt default recipes
- (Description)

**Comment by SilentChaos512** [comment]
I haven't tried it myself, but I'm told CraftTweaker can already remove any type of recipe.

**Comment by TheNimbleNinja** [comment]
it can remove crafting table and vanilla recipes by itself but you would have to add support for your machines for it to be able to remove your recipes

**Comment by Partonetrain** [comment]
It can remove any registered recipe type. For instance, `<recipetype:silentsmechanisms:alloy_smelter>.removeByName("silentsmechanisms:alloy_smelter/steel");`

It has an addJsonRecipe method too.

**Comment by SilentChaos512** [comment]
Thanks @Partonetrain. Looks like the correct line in that case is:

`<recipetype:silents_mechanisms:alloy_smelting>.removeByName("silents_mechanisms:alloy_smelting/steel");`

I'll add that to the wiki.

Also noticed JEI is only displaying recipe IDs for standard crafting recipes. Was it always like that? Guess I should add that to the tooltips if I can.
