### ISSUE TITLE
Configurable Sided Inputs/Outputs

### ISSUE THREAD

**Issue by AndyDL24** [SilentChaos512/Silents-Mechanisms#80]
## What Should Be Added or Changed?

- Hi, I would add the possibility to choose on which side to let the objects come out or to let the objects come in.

## Why Should This Be Done?

- Offers the possibility of placing one machine next to the other and the possibility of speeding up the crusher and cooking, in addition it makes it possible to understand where to attach cables for storage.
Thanks for the attention

**Comment by djmattyg007** [comment]
I think this is essential, otherwise things like Mekanism mechanical pipes get very confused when trying to extract the outputs of the refinery.

**Comment by SilentChaos512** [comment]
Definitely needs to be done eventually. Thankfully there are solutions to the problem currently. Refined storage can work around the issue easily by just connecting importers and exporters to the fluid machines, and storing the fluids in drives. Some mods also have filters on their pipes, but I'm not sure which (if any) have updated to 1.16 yet.
