### ISSUE TITLE
Steel ingots from other mods not working in recipes

### ISSUE THREAD

**Issue by StevenDoesStuffs** [SilentChaos512/Silents-Mechanisms#81]
Currently, the mod will not accept mekanism steel in recipes. I'm not sure if the other metals that are affected. It would be great if SM accepted ingots from any mod.

**Comment by SilentChaos512** [comment]
For reference, the ore dictionary no longer exists, we use vanilla's tag system. But I do see I'm not using the steel tags in the `silents_mechanisms:ingots/steels` tag. Will fix that.
