### ISSUE TITLE
Dust duplication

### ISSUE THREAD

**Issue by JaisDK** [SilentChaos512/Silents-Mechanisms#86]
## Versions

- **Silent's Mechanisms**: 1.15.2-0.7.2+52
- **Silent Lib**: 1.15.2-4.6.3+55
- **Forge**: 31.2.19
- **Modpack**: N/A

## Expected Behavior

- Having looked through the source code I expected a dupe bug to be present with the Crusher. 

## Actual Behavior

- Since chunks and dusts are added to the same tag it is possible to use the crusher together with any oredict converter like Mekanisms Oredictionificator. Just hook up the output from the crusher to the dict converter and convert the dust into chunks again. Run that back into the crusher and you have a 10% change to double your resource.

## Links/Images

- (Link)

## Steps to Reproduce the Problem

1. Setup a look between the output of a crusher to the input of an oredict converter (set to turn dust into chunks)
2. Route the oredict output back into the crusher

**Comment by JaisDK** [comment]
I don't see the reason for chunks being in the same tag as dust since they are not equivalent, why not use their own "chunks" tag?

**Comment by SilentChaos512** [comment]
They are tagged that way so that the second crushing is optional.

**Comment by JaisDK** [comment]
Wouldn't a second set of recipes for blasting, smelting and alloy_furnace using the chunks tag take care of the same thing?

**Comment by SilentChaos512** [comment]
I was hoping for full compatibility with other mods, but I guess that is asking for too much. It would be possible to modify the existing recipes to accept two different tags.

**Comment by JaisDK** [comment]
Haha, yea that's asking a bit too much :) These kinds of dupes have been around since the tekkit days.

**Comment by SilentChaos512** [comment]
Fixed in version 0.7.3 by commit 2bd5b254ef083fc2b8ceee32a7006ff0b6527537.
