### ISSUE TITLE
iron gold smelting

### ISSUE THREAD

**Issue by Ruvanal** [SilentChaos512/Silents-Mechanisms#90]
## Versions

- **Silent's Mechanisms**: 1.15.2-0.7.4+54
- **Silent Lib**:1.15.2-4.6.4+56
- **Forge**: 31.2.28
- **Modpack**: personal

## Expected Behavior
I expect to be able to smelt the iron/gold chunks and dust to their ingot form.  

## Actual Behavior
 There is no recipe shown for any of these 4 cases in JEI.  Placing the items in the electric furnace or minecraft furnace does nothing.

**Comment by SilentChaos512** [comment]
Figures I would miss something during the transition to data generators. Thanks for reporting.
