### ISSUE TITLE
Drying rack crashes game when trying to remove?

### ISSUE THREAD

**Issue by WispIV** [SilentChaos512/Silents-Mechanisms#92]
Silent Gear: SilentGear-1.15.2-1.7.5+106.jar

    Silent's Gems: 1.15.2-3.5.5+88.jar

    Silent Lib: SilentLib-1.15.2-4.6.4+56.jar

    Forge: forge-1.15.2-31.2.0

    Modpack: N/A

    Optifine Installed: Yes

## Expected Behavior
To drop when broken 

## Actual Behavior
It happened twice to another and myself.
I used the mattock and a friend used the lumber axe.
There was flesh/zombie leather on it while I tried to remove it and as soon as it's about to break the game crashes.
When I relaunch the rack is broken on the ground though.

## Steps to Reproduce the Problem

1.Place rack 
2.Add zombie flesh and wait to dry
3.Try to break rack with mattock, lumber axe or possibly normal axe

**Comment by SilentChaos512** [comment]
Got a crash report for this?

**Comment by WispIV** [comment]
[crash-2020-07-08_15.46.46-client.txt](https://github.com/SilentChaos512/Silents-Mechanisms/files/4892930/crash-2020-07-08_15.46.46-client.txt)

**Comment by SilentChaos512** [comment]
Looks like Optifine is at fault.

**Comment by WispIV** [comment]
Is it just the version do you think or Optifine in general?
Thank you for looking into it for me.

**Comment by SilentChaos512** [comment]
You could try updating Optifine if a newer version is available. I didn't even look at your Optifine version, I just saw Optifine in the stack trace. This doesn't crash with just my mods installed.

**Comment by WispIV** [comment]
Thank you :)
