### ISSUE TITLE
[1.15.2] Configs are not loaded

### ISSUE THREAD

**Issue by slava110** [SilentChaos512/Silents-Mechanisms#94]
## Versions

- **Silent's Mechanisms**: 0.7.5+56
- **Silent Lib**: 4.6.4+56
- **Forge**: 31.2.30
- **Modpack**: N/A

## Expected Behavior

- Configuration files should be loaded

## Actual Behavior

- Nothing changed in the game after config modification. Oil is still there, ores are still there...

## Links/Images

- Mod configuration: https://pastebin.com/h7i4ZV9N.

## Steps to Reproduce the Problem
- Try to modify config
- Nothing changed in the game

## Additional info

Also for some reason there's no configuration file in `config` folder. Only in `world\server-configs` folder. And I think it isn't loaded too :I

**Comment by SilentChaos512** [comment]
Those config keys are definitely wrong. I recently switched to Forge's config and changed some keys. Does seem like using server-type config was the wrong choice. I'll switch it to common.
