### ISSUE TITLE
Recipes for alloy smelting don't works

### ISSUE THREAD

**Issue by Emalios** [SilentChaos512/Silents-Mechanisms#95]
## Versions

- **KubeJs**: 2.7.1.3
- **MixinBootstrap**: 1.0.3
- **Silent's Mechanisms**: 0.7.6
- **Silent Lib**: 4.6.4
- **Forge**: 31.2.5
- **Modpack**: N/A

## Expected Behavior

- That recipes in silentm/data/recipes/alloy_smelting works

## Actual Behavior

- Recipes in silentm/data/recipes/alloy_smelting don't works

## Links/Images

- Recipe list of the alloy smelter : https://drive.google.com/file/d/1VxIclmEx8Ve6Wfa_j-v1KlV-fzMj1ivT/view?usp=sharing
- Recipes in data : https://drive.google.com/drive/folders/1uRAe84_gj2_WN7mMblpCRDX-JzoimGqC?usp=sharing

## Steps to Reproduce the Problem

1. Install kubejs and mixinbootstrap
2. Just look the craft list of alloy smelter

**Comment by SilentChaos512** [comment]
Probably nothing I can do if the issue only occurs with another mod installed. Please provide a log file.

**Comment by Emalios** [comment]
Here the latest.log : https://drive.google.com/file/d/1Tgd73klO8uhaYLsconbFtVjXVNSv01tL/view?usp=sharing

**Comment by SilentChaos512** [comment]
Looks like this needs to be reported to KubeJS. Not sure how that mod works, but it seems like something is intercepting recipes and failing on certain types. I also see errors for Silent Gear recipes in your log. First error is on line 475.

**Comment by Emalios** [comment]
I have find the bug thanks to a friend, in your json recipes, there is a "value": [] to have an array of items but to have an items array you have to write "values" : []

**Comment by SilentChaos512** [comment]
No, it will read the property with either `value` or `values`. The alloy smelter recipes in the latest version were created by a data generator. They contain no errors and load correctly without KubeJS installed.

**Comment by Emalios** [comment]
Yes, but here : https://github.com/SilentChaos512/Silents-Mechanisms/blob/b89dd56411dae0e49efde9d28479202226a53e3b/src/main/java/net/silentchaos512/mechanisms/data/recipes/AlloySmeltingRecipeBuilder.java#L99
You forgot to check if there are more than one ingredients right ?

**Comment by SilentChaos512** [comment]
That function serializes a single ingredient. Ingredients can be multiple items/tags. I changed the preferred name to `value` because it makes sense. I kept a check for `values` in the deserialize method for compatibility with existing data packs. I see no issue.
