### ISSUE TITLE
[MC 1.15.2|SM 0.7.6+57] Alloy Smelter output recipes not displaying in JEI.

### ISSUE THREAD

**Issue by gloomyMoron** [SilentChaos512/Silents-Mechanisms#99]
## Versions
- **Minecraft**: 1.15.2
- **Silent's Mechanisms**: 0.7.6+57
- **Silent Lib**: 4.6.6+59
- **Forge**: 31.2.31
- **Modpack**: Omnia 1.6.0
- **JEI**: 6.0.2.12

## Expected Behavior
- Able to view recipes for Alloys by either selecting the alloy or the Alloy Smelter in JEI

## Actual Behavior
- When attempting to view the recipes for alloys or recipes that the Alloy Smelter is capable of doing by left-clicking or pressing R on them in the inventory/JEI menu the recipes do not show. It shows the recipes that the Crusher accepts as well as the recipe for the machines themselves, just not the Alloy Smelter output recipes.

## Links/Images
-[ Imgur Image](https://imgur.com/a/csGBW3j)

## Steps to Reproduce the Problem
1. Press R or left-click an Alloy in the JEI menu or inventory.
________________________________________

It used to work in JEI in Omnia 1.5.0 but it no longer does. I don't know if that's 'cause a thing got borked in a crash or because of the updated version of Silent Mechanisms used in 1.6.0 of the mod pack. The previous version of Silent's Mechanisms was **0.7.2+52**, and the previous version of Silent Lib was **4.6.0+48**.

**Comment by gjheaton** [comment]
I am seeing the same issue. But I am also not able to craft any alloys in the alloy smelter.

**Comment by gloomyMoron** [comment]
@gjheaton Now that you mention it... same here. Can't even do the Alloys that this mod adds.

**Comment by SilentChaos512** [comment]
Could I get a log file from someone please?

**Comment by gloomyMoron** [comment]
I just installed JAOPCA, I'll see if that helps, but this is the log from the time before this current one where I still had the issue. I also have the "shutdown" log and the "debug" log, if those'll help.
https://paste.feed-the-beast.com/view/42cf2be3

Edit: JAOPCA didn't fix the issue.

**Comment by SilentChaos512** [comment]
Ah, must be the same as #95. I believe KubeJS is responsible. Nothing I can do about it.
